### ISSUE TITLE
Including a nonexistent resource should respond with a 400

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#14]
This works:
perl -Ilib -MPONAPI::Client -MData::Dumper -E 'my $p = PONAPI::Client->new(); warn Dumper( $p->retrieve(type => "articles", id => 2, include => [qw/comments/]) )'

From my understanding of the spec (http://jsonapi.org/format/#fetching-includes) this should give me a 400:
perl -Ilib -MPONAPI::Client -MData::Dumper -E 'my $p = PONAPI::Client->new(); warn Dumper( $p->retrieve(type => "articles", id => 2, include => [qw/asdasd comments.not_there/]) )'

Instead, it gives me the same result as if I hadn't used include at all.

**Comment by mickeyn** [comment]
fixed. but why don't we have a test for it? :)

**Comment by mickeyn** [comment]
we should rethink the part where the repository sets the error status... this is a spec thing and we lose the control over enforcing the correct status by allowing the repository to decide on it.

update: opened #29 as a separate issue.

**Comment by mickeyn** [comment]
added the tests in 075ba1f
