### ISSUE TITLE
Review Dancer Usage

### ISSUE THREAD

**Issue by stevan** [mickeyn/PONAPI#20]
Lets be sure that Dancer is actually helping us and not hurting us.

**Comment by mickeyn** [comment]
current master using an in-house Plack based replacement, though I tend to keep the Dancer2 implementation as an option (it's free since it was already done) so I didn't remove it but kept both under the Server/ dir (this will also allow other implementations to be thrown in there).

reasonable?

**Comment by mickeyn** [comment]
closing for now, the Dancer2 server is not actually being used
