### ISSUE TITLE
Include PONAPI version information in Transaction

### ISSUE THREAD

**Issue by stevan** [mickeyn/PONAPI#26]
Client and Server should include PONAPI version information in Request and Response.

This can be either in HTTP headers (`X-PONAPI-Server-Version`, `X-PONAPI-Client-Version`) or just an additional key in a `meta` info.

**Comment by mickeyn** [comment]
added in 25e800d

can be opt out in server configuration `{ponapi}{server}{send_version_header}` or client using `Client->new( send_version_header => 0 )`.

keeping open till tests are added.

**Comment by mickeyn** [comment]
we have a test now
