### ISSUE TITLE
Responses for updating resources

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#34]
http://jsonapi.org/format/#crud-updating-responses

Spec sez:
200 OK
If a server accepts an update but also changes the resource(s) in ways other than those specified by the request (for example, updating the updated-at attribute or a computed sha), it MUST return a 200 OK response. The response document MUST include a representation of the updated resource(s) as if a GET request was made to the request URL.

That presents a handful of complications depending on how the underlaying repo is implement, e.g. replication delay.

We could solve this by having each resource say whether we need to wait in case of a 200, or if we can return immediately; or a server side configuration to turn all update-successful 200s into 202s, since the spec also says:
202 Accepted
If an update request has been accepted for processing, but the processing has not been completed by the time the server responds, the server MUST return a 202 Accepted status code.

Or something else? :)

**Comment by mickeyn** [comment]
this was handled, we can close it for now
