### ISSUE TITLE
json api version is hardcoded lib/PONAPI/Builder/Document.pm

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#39]
See $title. We need to pass it to the DAO, the request object, the document builder, and maybe to the repo too.

**Comment by Hugmeir** [comment]
With that code merged, the code now picks the correct version.. probably :) Let's add some tests changing the version!

**Comment by mickeyn** [comment]
it works - but I tested it manually :)
indeed, let's add the tests (we need to support code overriding for the config in server creation)

**Comment by mickeyn** [comment]
added the config overriding + tests: 15b1ce1
