### ISSUE TITLE
How should repos add pagination links?

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#46]
http://jsonapi.org/format/#fetching-pagination

Starting with this request:

```
GET /retrieve/articles?page[offset]=15000&page[limit]=5000
```

If the repo then wants to add pagination links, currently they have to construct the urls themselves. I'm thinking we should add something to make that simpler; maybe as simple as passing a hash to ->get_self_link() that will turn those into a url.

Side note: This code might need to be shared between client and server.

**Comment by stevan** [comment]
Why not add a `->build_pagination_links( offset => ..., limit => ... )`?

**Comment by Hugmeir** [comment]
Sadly, the pagination strategy is up to the repo, so having a method that gets offset+limit is too constrictive.

https://github.com/mickeyn/PONAPI/commit/2e0dc86d19642c96c07ee70bf83e43735076a28f
Currently I'm doing this on a branch -- the interesting bits are _add_pagination_links in MockDB, and add_pagination_links in Document. Basically, the repo is passing

```
prev => { offset => 8, limit => 4 },
self  => { offset => 12, limit => 4 },
next => { offset => 16, limit => 4 },
etc etc
```

And we let the Document builder handle creating the url. But it did mean copypasting a chunk of code out of the client.

One (of many) problem with that approach is that we'll need to expand it to also take sort, since without that pagination is dodgy.

**Comment by Hugmeir** [comment]
Closing this, since it's really up to the repo, and more than that, to the type itself. When/If we release repo wrappers for DBIx::Class and/or Class::DBI, we can address that there.
