### ISSUE TITLE
self links are broken for retrieve_(by_)relationships

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#47]
`GET /articles/2/authors` responds with `self => 'people/88'`; similarly, `GET /articles/2/comments` responds with `self => '/comments'`.

This is because PONAPI::Builder::Document::get_self_link uses the first resource builder the build the self link

**Comment by mickeyn** [comment]
Yeah, I think we might need to move the link generation to the inherited request objects and the addition of the link to `self => $link` to the parent class (`DAO::Requset`).

I can hack on it tomorrow morning.

**Comment by mickeyn** [comment]
this was fixed in #49
