### ISSUE TITLE
Test PONAPI::Client

### ISSUE THREAD

**Issue by stevan** [mickeyn/PONAPI#6]
Look at Test::TCP to solve this, you can look here (https://metacpan.org/source/MIYAGAWA/Plack-1.0037/lib/Plack/Test/Server.pm) to see how Plack does it.

**Comment by Hugmeir** [comment]
The bulk of testing for the client currently happens in the server. I'm not sure if that's enough to close this.

We could have roughly a clone of t/030-Server/003-with-client.t in the client tests, I suppose?

**Comment by mickeyn** [comment]
We agreed this is not needed and not blocking for the release.
As we discussed, the server is going to have most development focus and will always have the client covering tests maintained and improved.
