### ISSUE TITLE
Ponder a PONAPI::Uri module

### ISSUE THREAD

**Issue by stevan** [mickeyn/PONAPI#7]
We have a need to handle the PONAPI specific URI forms (ex: "foo[bar]=1", "baz=1,2,3,4", etc). We have a need to both read and write these URIs. 

The server will need to write these URIs when building `link` sections, it also needs to read them when they come in via HTTP requests.

The client will need to write these URIs when building a HTTP request, and also to read them when they are embedded into a `links` section of a document.

**Comment by mickeyn** [comment]
have a simple implementation ready (locally), will test tomorrow on Client and Plugin::Params

**Comment by mickeyn** [comment]
added in 4898845
