### ISSUE TITLE
What is a repository?

### ISSUE THREAD

**Issue by markblackman** [mickeyn/PONAPI#75]
The "repository" noun appears to be the most critical concept in the entire implementation, however, I am unable to find a sentence in the documentation that defines the repository at any level or references a definition. Could we add one please?

**Comment by mickeyn** [comment]
The repository is your data storage. can be a DB, static data, ES, whatever.
Would you like to submit a patch to reflect the explanation the way you expected to see it in the docs?

**Comment by markblackman** [comment]
Thanks for the reply.  What's an ES? external service, event stream, external system, external storage?

In particular, what characteristics of the data in the data storage does the implementation rely on? As JSONAPI is a kind of attempt to permit JSON to act as hypermedia, there's an assumption that useful relationships exist between various subsets of the data (or you wouldn't bother with JSONAPI).  JSONAPI feels like a lightweight reimplementation of XML at times.

Simply some text like ...

"JSONAPI and hence PONAPI provide views of resources in your resource repository and permits exposing relationships between resources in the repository. A repository, in this context, is nothing more than an abstract collection of resources, which might be realised as an RDBMS, static data in what ever storage format, or any storage of resources you can have available. Crucially, JSONAPI assumes that useful relationships can be expressed between sets of resources in the resource repository and that it is possible to write methods in the repository classes that return the resources in the relationship."

In particular, PONAPI respository relationships appear to map fairly closely to the relationships in DBIx::Class, so any RDBMS representation can be ported to PONAPI with a minimum of conceptual effort, although some mechanical effort is required.

I am unsure if that second paragraph is accurate, but it was the impression I got from reading the documentation. Anyway, you're welcome to butcher or ignore that text. I would quite like to use PONAPI, but it felt like it was taking too long to understand how to map a non-RDBMS resource model into the PONAPI repository. I am unsure I understand what the author's expectations are for the repository, except for the RDBMS case.

**Comment by mickeyn** [comment]
ES = Elasticsearch :) it was just an example for a storage form

The thing is, PONAPI doesn't make assumptions about your data, the only requirement is to create an API (the repository module) that we can use to interact with it. behind the scenes (your module) have it anyway you like, and if the mapping resembles DBIC or whatever, that only means it's gonna be easier for you to hook your data into PONAPI.

**Comment by stevan** [comment]
@markblackman JSONAPI is definitely skewed towards a relational data model, but it is absolutely not required. 

Given a set of relational data, you can take advantage of many of the features of JSONAPI to model those relationships in a sensible and efficient way. Your JSONAPI document can include as many or as few of the relationships as you like and also additionally include related entities in the way you (the author) chooses while allowing the user (using the `include` directives in the query-string) to also have a level of control. Here the mapping to a traditional RDBMS relational data model is obvious and clear, but still we have a layer of indirection (the `Repository`) which allows you to preserve the encapsulation of your original data source. 

Given a set of structured (aka - nested) data with little or no external relations (your typical NoSQL schema), there are some JSONAPI features that may not seem very useful to you (relationships, included entities, etc.). However, this does not necessarily have to be the case, as I said above, JSONAPI provides the level of indirection to allow you to make a decision about how your data is presented via your service. The resulting encapsulation means that you can choose to model your structured data in whatever way you like, including breaking up your data into a core element with nested elements modeled as relations (just as if it was held in a RDBMS). 

While it is often convenient to just expose your data model exactly as it is via a REST service, it is almost always _not_ what you actually want to do, for all the same reasons that encapsulation is one of the central tenants of OO programming. The whole point of the PONAPI concept of a Repository is to encourage people to think about this and to use this level of indirection to build a sensible view on their data which may (or may not) map directly to the underlying data source's model.

**Comment by markblackman** [comment]
Thanks, all great expansions. I'd consider adding some of that to the manual or the POD.  Although, I think JSONAPI does assume you can define one or more useful collections of resources (however abstracted compared to your data source model) which might have relationships between the resources of the same type or another type.  The answer to my original query, based on this conversation is something like "A repository is a set of collections of resources which may or may not directly reflect your data source model. Your repository class merely needs to define sensible behaviours for the required methods in Repository.pm".

**Comment by stevan** [comment]
@markblackman yes, that is a good summary, perhaps you could add that into one of the POD docs via a pull request?

**Comment by markblackman** [comment]
Pull request submitted
