### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by merkys** [mickeyn/PONAPI#89]
I see that there is a wrapper for YAHC UA which is able to do HTTPS queries. However, I can't find no way to replace Hijk with YAHC, and pass the SSL parameters to it.

**Comment by mickeyn** [comment]
When creating a Client object, you can pass in a `ua` object as an argument.

You can create the object using `PONAPI::Client::UA::YAHC` to have ready-made support for `YAHC`.

Alternatively, you can wrap any `ua` object you like to use with a wrapping object which consumes `PONAPI::Client::Role::UA` to ensure `PONAPI::Client` can interact with it.

**Comment by merkys** [comment]
Thanks for quick response. Passing `ua` argument worked. I had to make small changes to `PONAPI::Client::UA::YAHC`, will submit a PR with them.
